from __future__ import annotations

STATUS_REVIEW_PENDING = "review_pending"
STATUS_AUTO_ASSIGNED = "auto_assigned"
STATUS_HUMAN_CONFIRMED = "human_confirmed"
STATUS_HUMAN_CORRECTED = "human_corrected"
STATUS_REJECTED = "rejected"

POSITIVE_ASSIGNMENT_STATUSES: tuple[str, ...] = (
    STATUS_HUMAN_CONFIRMED,
    STATUS_HUMAN_CORRECTED,
)

SEARCH_RECALL_ASSIGNMENT_STATUSES: tuple[str, ...] = (
    STATUS_HUMAN_CONFIRMED,
    STATUS_HUMAN_CORRECTED,
    STATUS_AUTO_ASSIGNED,
)

ASSIGNMENT_STATUS_WEIGHT: dict[str, float] = {
    STATUS_HUMAN_CONFIRMED: 1.0,
    STATUS_HUMAN_CORRECTED: 1.0,
    STATUS_AUTO_ASSIGNED: 0.82,
}
